- id: automation_living_room_lights
  alias: Scene Living Room
  initial_state: true
  trigger:
    platform: state
    entity_id: input_select.scene_livingroom
  action:
    - service: hue.hue_activate_scene
      data_template:
        group_name: Living Room
        scene_name: "{{ states('input_select.scene_livingroom') }}"
- id: automation_kitchen_lights
  alias: Scene Kitchen
  initial_state: true
  trigger:
    platform: state
    entity_id: input_select.scene_kitchen
  action:
    - service: hue.hue_activate_scene
      data_template:
        group_name: Kitchen
        scene_name: "{{ states('input_select.scene_kitchen') }}"
- id: automation_bedroom_lights
  alias: Scene Bedroom
  initial_state: true
  trigger:
    platform: state
    entity_id: input_select.scene_bedroom
  action:
    - service: hue.hue_activate_scene
      data_template:
        group_name: Bedroom
        scene_name: "{{ states('input_select.scene_bedroom') }}"
- id: sunset
  alias: Sunset
  trigger:
    platform: sun
    event: sunset
    offset: -00:45:00
  condition:
    condition: state
    entity_id: input_boolean.occupancy_mode
    state: "on"
  action:
    - service: script.turn_on_lights
- id: night_lighting
  alias: Night Lighting
  trigger:
    platform: time
    at: 00:00:00
  condition:
    - condition: state
      entity_id: input_boolean.occupancy_mode
      state: "on"
    - condition: state
      entity_id: group.living_room_lights
      state: "on"
  action:
    - service: hue.hue_activate_scene
      data_template:
        group_name: Bedroom
        scene_name: Read
    - service: hue.hue_activate_scene
      data_template:
        group_name: Kitchen
        scene_name: Relax
  initial_state: "on"
- id: ifttt_webhook
  alias: IFTTT Webhook
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    service_template: "{{ trigger.event.data.service }}"
    data_template:
      entity_id: "{{ trigger.event.data.entity_id }}"
- id: family_away
  alias: Family Away
  trigger:
    - entity_id: group.family
      from: home
      platform: state
      to: not_home
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.occupancy_mode
  initial_state: "on"
- id: danny_away
  alias: Danny Away
  trigger:
    - entity_id: input_boolean.danny_home
      from: "on"
      platform: state
      to: "off"
  action:
    - service: device_tracker.see
      data:
        dev_id: danny
        location_name: not_home
- id: danny_home
  alias: Danny Home
  trigger:
    - entity_id: input_boolean.danny_home
      from: "off"
      platform: state
      to: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.occupancy_mode
    - service: device_tracker.see
      data:
        dev_id: danny
        location_name: home
  initial_state: "on"
- id: maire_away
  alias: Maire Away
  trigger:
    - entity_id: input_boolean.maire_home
      from: "on"
      platform: state
      to: "off"
  action:
    - service: device_tracker.see
      data:
        dev_id: maire
        location_name: not_home
- id: maire_home
  alias: Maire Home
  trigger:
    - entity_id: input_boolean.maire_home
      from: "off"
      platform: state
      to: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.occupancy_mode
    - service: device_tracker.see
      data:
        dev_id: maire
        location_name: home
  initial_state: "on"
# Occupancy logic
- id: occupied
  alias: Occupied
  trigger:
    - entity_id: input_boolean.occupancy_mode
      from: "off"
      platform: state
      to: "on"
  action:
    - service: script.welcome_home
  initial_state: "on"
- id: unoccupied
  alias: Unoccupied
  trigger:
    - entity_id: input_boolean.occupancy_mode
      from: "on"
      platform: state
      to: "off"
  action:
    - service: script.interior_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.danny_home
    - service: input_boolean.turn_off
      entity_id: input_boolean.maire_home
  initial_state: "on"
# Phone charging logic
- id: danny_phone_charging
  alias: "Danny Phone Charging"
  initial_state: "on"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "danny_phone_charging"
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.danny_phone_charging
- id: danny_phone_unplugged
  alias: "Danny Phone Unplugged"
  initial_state: "on"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "danny_phone_unplugged"
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.danny_phone_charging
- id: maire_phone_charging
  alias: "Maire Phone Charging"
  initial_state: "on"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "maire_phone_charging"
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.maire_phone_charging
- id: maire_phone_unplugged
  alias: "Maire Phone Unplugged"
  initial_state: "on"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: "maire_phone_unplugged"
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.maire_phone_charging

# Sleeping logic
- id: going_to_sleep
  alias: "Going to sleep"
  initial_state: "on"
  trigger:
    - entity_id: input_boolean.danny_phone_charging
      from: "off"
      platform: state
      to: "on"
    - entity_id: input_boolean.maire_phone_charging
      from: "off"
      platform: state
      to: "on"
  condition:
    # Both phones need to be plugged in to trigger
    - condition: state
      entity_id: input_boolean.danny_phone_charging
      state: "on"
    - condition: state
      entity_id: input_boolean.maire_phone_charging
      state: "on"
    # We have to be home
    - condition: state
      entity_id: input_boolean.occupancy_mode
      state: "on"
    # It's best if the bedroom light is on (iffiest condition)
    - condition: state
      entity_id: light.bed_lamp
      state: "on"
  action:
    - service: script.go_to_sleep
